#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
cd $DIR

jekyll build  --config _config.yml,_config_normal.yml
rsync -v -a -e "ssh" _site/tutorials biojs:biojs
rsync -v -a -e "ssh" _site/css biojs:biojs
rsync -v -a -e "ssh" _site/img biojs:biojs

# create archives of the whole website to download

BUILD="_build/"
BUILD=$(cd "$BUILD" && pwd )
echo $BUILD


rm -rf "$BUILD"
mkdir -p "$BUILD"

(
cd _site
tar -czvf "$BUILD"/site.tar.gz *
zip -r "$BUILD"/site.zip *
)

echo "Options +Indexes
IndexOptions +FancyIndexing" > "$BUILD"/.htaccess

rsync -v -a --delete -e "ssh" "$BUILD"/ biojs:biojs/site-download


)
