#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
cd $DIR

jekyll build  --config _config.yml,_config_normal.yml
rsync -v -a -e "ssh" _site/tutorials biojs:biojs
rsync -v -a -e "ssh" _site/css biojs:biojs
rsync -v -a -e "ssh" _site/img biojs:biojs
)
